### ISSUE TITLE
Make Gatby v5 Compatible 

### ISSUE THREAD

**Issue by kyro-D** [chadly/gatsby-plugin-env-variables#27]
Plugin doesn't list Gatsby version 5 as a peer dependency. Running `npm install` in my project with this package generates an npm error `npm ERR! ERESOLVE unable to resolve dependency tree`. [Relevant documentation](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v4-to-v5/#updating-community-plugins). Just wanted to bring this to the maintainers' attention 😁

**Comment by chadly** [comment]
👍 seems like a straightforward fix.

if you submit a PR, I will review it. 😁

**Comment by TannerJuby1** [comment]
PR Submitted: https://github.com/chadly/gatsby-plugin-env-variables/pull/28

**Comment by TannerJuby1** [comment]
@chadly any idea when the PR resolving this issue can get looked at? This issue is currently holding up our ability to release our latest updates to our website

**Comment by kyro-D** [comment]
Closing due to #28 being merged 😄

**Comment by kyro-D** [comment]
Reopening because release hasn't been updated yet. Will close when release is pushed through.

**Comment by chadly** [comment]
`v2.3.0` is [released](https://github.com/chadly/gatsby-plugin-env-variables/releases/tag/v2.3.0)
